services:
  backend:
    image: notme-backend
    env_file: backend/dockerfile.env
    build:
      context: backend/
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "./backend:/noteme-backend"
    ports:
      - "7900:7900"






